export interface Player {
  id: number;
  name: string;
  country: string;
  image: string;
  fifa_points: number;
  biography: string;
  statistics: string;
  trophees_majeurs: string;
  age: number;
  club: string;
  nationalite: string;
  buts: number;
  passes: number;
  cartons_jaunes: number;
  cartons_rouges: number;
}

export const joueursParPoste = {
  gardiens: [
    {
      id: 1,
      name: 'Manuel Neuer',
      country: 'Allemagne',
      image: 'https://example.com/neuer.jpg',
      fifa_points: 90,
      biography: 'Gardien de but légendaire...',
      statistics: '20 clean sheets en Bundesliga',
      trophees_majeurs: 'Coupe du Monde 2014',
      age: 35,
      club: 'Bayern Munich',
      nationalite: 'Allemand',
      buts: 0,
      passes: 5,
      cartons_jaunes: 1,
      cartons_rouges: 0,
    },
  ],
  defenseursCentraux: [
    {
      id: 2,
      name: 'Virgil van Dijk',
      country: 'Pays-Bas',
      image: 'https://example.com/vandijk.jpg',
      fifa_points: 89,
      biography: 'Défenseur central solide et rapide...',
      statistics: '100 matchs joués',
      trophees_majeurs: 'Premier League',
      age: 30,
      club: 'Liverpool',
      nationalite: 'Néerlandais',
      buts: 5,
      passes: 3,
      cartons_jaunes: 2,
      cartons_rouges: 0,
    },
  ],
  arrieresGauche: [
    {
      id: 3,
      name: 'Andrew Robertson',
      country: 'Écosse',
      image: 'https://example.com/robertson.jpg',
      fifa_points: 87,
      biography: 'Arrière gauche rapide et technique...',
      statistics: '10 passes décisives',
      trophees_majeurs: 'Premier League',
      age: 27,
      club: 'Liverpool',
      nationalite: 'Écossais',
      buts: 1,
      passes: 10,
      cartons_jaunes: 2,
      cartons_rouges: 0,
    },
  ],
  arrieresDroits: [
    {
      id: 4,
      name: 'Trent Alexander-Arnold',
      country: 'Angleterre',
      image: 'https://example.com/arnold.jpg',
      fifa_points: 88,
      biography: 'Arrière droit offensif avec de nombreuses passes décisives...',
      statistics: '15 passes décisives',
      trophees_majeurs: 'Premier League',
      age: 23,
      club: 'Liverpool',
      nationalite: 'Anglais',
      buts: 2,
      passes: 15,
      cartons_jaunes: 1,
      cartons_rouges: 0,
    },
  ],
  milieuxDefensifs: [
    {
      id: 5,
      name: "N'Golo Kanté",
      country: 'France',
      image: 'https://example.com/kante.jpg',
      fifa_points: 89,
      biography: 'Milieu défensif infatigable...',
      statistics: '80 tacles réussis',
      trophees_majeurs: 'Coupe du Monde 2018',
      age: 29,
      club: 'Chelsea',
      nationalite: 'Français',
      buts: 3,
      passes: 5,
      cartons_jaunes: 3,
      cartons_rouges: 0,
    },
  ],
  milieuxCentraux: [
    {
      id: 6,
      name: 'Luka Modrić',
      country: 'Croatie',
      image: 'https://example.com/modric.jpg',
      fifa_points: 88,
      biography: 'Milieu central technique et expérimenté...',
      statistics: '85 passes réussies',
      trophees_majeurs: "Ballon d'Or 2018",
      age: 34,
      club: 'Real Madrid',
      nationalite: 'Croate',
      buts: 5,
      passes: 8,
      cartons_jaunes: 2,
      cartons_rouges: 0,
    },
  ],
  milieuxOffensifs: [
    {
      id: 7,
      name: 'Kevin De Bruyne',
      country: 'Belgique',
      image: 'https://example.com/debruyne.jpg',
      fifa_points: 91,
      biography: 'Milieu offensif complet, excellent passeur...',
      statistics: '20 buts, 25 passes',
      trophees_majeurs: 'Premier League',
      age: 29,
      club: 'Manchester City',
      nationalite: 'Belge',
      buts: 20,
      passes: 25,
      cartons_jaunes: 2,
      cartons_rouges: 0,
    },
  ],
  ailiersGauche: [
    {
      id: 8,
      name: 'Sadio Mané',
      country: 'Sénégal',
      image: 'https://example.com/mane.jpg',
      fifa_points: 90,
      biography: 'Ailier gauche rapide et technique...',
      statistics: '25 buts',
      trophees_majeurs: 'Premier League',
      age: 28,
      club: 'Liverpool',
      nationalite: 'Sénégalais',
      buts: 25,
      passes: 10,
      cartons_jaunes: 1,
      cartons_rouges: 0,
    },
  ],
  ailiersDroits: [
    {
      id: 9,
      name: 'Mohamed Salah',
      country: 'Égypte',
      image: 'https://example.com/salah.jpg',
      fifa_points: 91,
      biography: 'Ailier droit puissant et efficace...',
      statistics: '30 buts',
      trophees_majeurs: 'Premier League',
      age: 28,
      club: 'Liverpool',
      nationalite: 'Égyptien',
      buts: 30,
      passes: 8,
      cartons_jaunes: 1,
      cartons_rouges: 0,
    },
  ],
  attaquants: [
    {
      id: 10,
      name: 'Robert Lewandowski',
      country: 'Pologne',
      image: 'https://example.com/lewandowski.jpg',
      fifa_points: 92,
      biography: 'Attaquant central prolifique...',
      statistics: '40 buts',
      trophees_majeurs: 'Bundesliga',
      age: 32,
      club: 'Bayern Munich',
      nationalite: 'Polonais',
      buts: 40,
      passes: 5,
      cartons_jaunes: 1,
      cartons_rouges: 0,
    },
  ],
  secondsAttaquants: [
    {
      id: 11,
      name: 'Lionel Messi',
      country: 'Argentine',
      image: 'https://example.com/messi.jpg',
      fifa_points: 93,
      biography: 'Second attaquant exceptionnel...',
      statistics: '30 buts, 20 passes',
      trophees_majeurs: "Ballon d'Or",
      age: 33,
      club: 'Paris Saint-Germain',
      nationalite: 'Argentin',
      buts: 30,
      passes: 20,
      cartons_jaunes: 1,
      cartons_rouges: 0,
    },
  ],
};
