import { Joueur } from '@shared/types/joueurs';

export const ailiersGauches: Joueur[] = [
  {
    id: 81,
    name: "Cristiano Ronaldo",
    posteId: 9,
    country: "Portugal",
    image: "ronaldo.jpg",
    fifa_points: 98,
    biography: "Meilleur buteur de l'histoire du football, 5 Ballons d’Or.",
    statistics: "1200+ matchs",
    trophees_majeurs: "Champions League, EURO 2016",
    age: 40,
    club: "Al-Nassr",
    nationalite: "Portugais",
    buts: 890,
    passes: 280,
    cartons_jaunes: 120,
    cartons_rouges: 11,
  },
  {
    id: 82,
    name: "George Best",
    posteId: 9,
    country: "Irlande du Nord",
    image: "george_best.jpg",
    fifa_points: 94,
    biography: "Génie imprévisible de Manchester United.",
    statistics: "470+ matchs",
    trophees_majeurs: "Ballon d’Or 1968",
    age: 59,
    club: "Retraité",
    nationalite: "Nord-Irlandais",
    buts: 180,
    passes: 110,
    cartons_jaunes: 20,
    cartons_rouges: 1,
  },
  {
    id: 83,
    name: "Franck Ribéry",
    posteId: 9,
    country: "France",
    image: "ribery.jpg",
    fifa_points: 90,
    biography: "Ailier explosif, finaliste Ballon d’Or 2013.",
    statistics: "700+ matchs",
    trophees_majeurs: "Champions League, Bundesliga",
    age: 42,
    club: "Retraité",
    nationalite: "Français",
    buts: 150,
    passes: 170,
    cartons_jaunes: 40,
    cartons_rouges: 2,
  },
  {
    id: 84,
    name: "Sadio Mané",
    posteId: 9,
    country: "Sénégal",
    image: "mane.jpg",
    fifa_points: 91,
    biography: "Leader du Sénégal et star de Liverpool.",
    statistics: "500+ matchs",
    trophees_majeurs: "Champions League, CAN 2022",
    age: 33,
    club: "Al-Nassr",
    nationalite: "Sénégalais",
    buts: 220,
    passes: 95,
    cartons_jaunes: 18,
    cartons_rouges: 0,
  },
  {
    id: 85,
    name: "Eden Hazard",
    posteId: 9,
    country: "Belgique",
    image: "hazard.jpg",
    fifa_points: 89,
    biography: "Ailier technique, capitaine des Diables Rouges.",
    statistics: "600+ matchs",
    trophees_majeurs: "Europa League",
    age: 34,
    club: "Retraité",
    nationalite: "Belge",
    buts: 160,
    passes: 140,
    cartons_jaunes: 15,
    cartons_rouges: 1,
  },
  {
    id: 86,
    name: "Ryan Giggs",
    posteId: 9,
    country: "Pays de Galles",
    image: "giggs.jpg",
    fifa_points: 91,
    biography: "Légende de Manchester United, longévité exemplaire.",
    statistics: "950+ matchs",
    trophees_majeurs: "Champions League, Premier League",
    age: 51,
    club: "Retraité",
    nationalite: "Gallois",
    buts: 170,
    passes: 240,
    cartons_jaunes: 30,
    cartons_rouges: 1,
  },
  {
    id: 87,
    name: "Leroy Sané",
    posteId: 9,
    country: "Allemagne",
    image: "sane.jpg",
    fifa_points: 86,
    biography: "Vitesse et frappe puissante.",
    statistics: "400+ matchs",
    trophees_majeurs: "Bundesliga, Premier League",
    age: 29,
    club: "Bayern Munich",
    nationalite: "Allemand",
    buts: 100,
    passes: 90,
    cartons_jaunes: 10,
    cartons_rouges: 0,
  },
  {
    id: 88,
    name: "Kingsley Coman",
    posteId: 9,
    country: "France",
    image: "coman.jpg",
    fifa_points: 87,
    biography: "A marqué le but décisif en finale de C1 2020.",
    statistics: "350+ matchs",
    trophees_majeurs: "Champions League, Bundesliga",
    age: 29,
    club: "Bayern Munich",
    nationalite: "Français",
    buts: 80,
    passes: 70,
    cartons_jaunes: 8,
    cartons_rouges: 0,
  },
  {
    id: 89,
    name: "Vinícius Júnior",
    posteId: 9,
    country: "Brésil",
    image: "vinicius.jpg",
    fifa_points: 90,
    biography: "Étoile montante du Real Madrid.",
    statistics: "250+ matchs",
    trophees_majeurs: "Champions League, Liga",
    age: 25,
    club: "Real Madrid",
    nationalite: "Brésilien",
    buts: 85,
    passes: 60,
    cartons_jaunes: 12,
    cartons_rouges: 1,
  },
  {
    id: 90,
    name: "Jack Grealish",
    posteId: 9,
    country: "Angleterre",
    image: "grealish.jpg",
    fifa_points: 85,
    biography: "Joueur élégant, champion d’Europe avec City.",
    statistics: "300+ matchs",
    trophees_majeurs: "Champions League, Premier League",
    age: 29,
    club: "Manchester City",
    nationalite: "Anglais",
    buts: 60,
    passes: 85,
    cartons_jaunes: 10,
    cartons_rouges: 0,
  },
];
