import { Joueur } from '@shared/types/joueurs';

export const ailiersDroits: Joueur[] = [
  {
    id: 71,
    name: "Lionel Messi",
    posteId: 8,
    country: "Argentine",
    image: "messi.jpg",
    fifa_points: 98,
    biography: "L’un des plus grands joueurs de tous les temps, 8 Ballons d’Or.",
    statistics: "1000+ matchs",
    trophees_majeurs: "Coupe du Monde, Champions League, Copa America",
    age: 37,
    club: "Inter Miami",
    nationalite: "Argentin",
    buts: 820,
    passes: 350,
    cartons_jaunes: 80,
    cartons_rouges: 3,
  },
  {
    id: 72,
    name: "Garrincha",
    posteId: 8,
    country: "Brésil",
    image: "garrincha.jpg",
    fifa_points: 94,
    biography: "Magicien du dribble, double champion du monde.",
    statistics: "600+ matchs",
    trophees_majeurs: "2 Coupes du Monde",
    age: 49,
    club: "Retraité",
    nationalite: "Brésilien",
    buts: 230,
    passes: 120,
    cartons_jaunes: 5,
    cartons_rouges: 1,
  },
  {
    id: 73,
    name: "Arjen Robben",
    posteId: 8,
    country: "Pays-Bas",
    image: "robben.jpg",
    fifa_points: 90,
    biography: "Spécialiste du crochet intérieur et des frappes enroulées.",
    statistics: "700+ matchs",
    trophees_majeurs: "Champions League, Bundesliga",
    age: 41,
    club: "Retraité",
    nationalite: "Néerlandais",
    buts: 210,
    passes: 120,
    cartons_jaunes: 20,
    cartons_rouges: 1,
  },
  {
    id: 74,
    name: "Luis Figo",
    posteId: 8,
    country: "Portugal",
    image: "figo.jpg",
    fifa_points: 89,
    biography: "Ballon d’Or 2000, ailier élégant et technique.",
    statistics: "700+ matchs",
    trophees_majeurs: "Champions League",
    age: 52,
    club: "Retraité",
    nationalite: "Portugais",
    buts: 130,
    passes: 180,
    cartons_jaunes: 30,
    cartons_rouges: 2,
  },
  {
    id: 75,
    name: "Mohamed Salah",
    posteId: 8,
    country: "Égypte",
    image: "salah.jpg",
    fifa_points: 91,
    biography: "Star de Liverpool, vitesse et efficacité.",
    statistics: "600+ matchs",
    trophees_majeurs: "Champions League, Premier League",
    age: 33,
    club: "Liverpool",
    nationalite: "Égyptien",
    buts: 250,
    passes: 110,
    cartons_jaunes: 12,
    cartons_rouges: 0,
  },
  {
    id: 76,
    name: "Raheem Sterling",
    posteId: 8,
    country: "Angleterre",
    image: "sterling.jpg",
    fifa_points: 87,
    biography: "Percutant et technique, référence en Premier League.",
    statistics: "550+ matchs",
    trophees_majeurs: "Premier League",
    age: 30,
    club: "Chelsea",
    nationalite: "Anglais",
    buts: 130,
    passes: 90,
    cartons_jaunes: 25,
    cartons_rouges: 1,
  },
  {
    id: 77,
    name: "Ousmane Dembélé",
    posteId: 8,
    country: "France",
    image: "dembele.jpg",
    fifa_points: 86,
    biography: "Ambidextre et rapide, talent brut.",
    statistics: "400+ matchs",
    trophees_majeurs: "Coupe du Monde",
    age: 28,
    club: "PSG",
    nationalite: "Français",
    buts: 80,
    passes: 95,
    cartons_jaunes: 15,
    cartons_rouges: 0,
  },
  {
    id: 78,
    name: "Hakim Ziyech",
    posteId: 8,
    country: "Maroc",
    image: "ziyech.jpg",
    fifa_points: 85,
    biography: "Technicien hors pair et passeur de génie.",
    statistics: "350+ matchs",
    trophees_majeurs: "Eredivisie, Ligue Europa",
    age: 32,
    club: "Galatasaray",
    nationalite: "Marocain",
    buts: 75,
    passes: 100,
    cartons_jaunes: 10,
    cartons_rouges: 1,
  },
  {
    id: 79,
    name: "Angel Di Maria",
    posteId: 8,
    country: "Argentine",
    image: "di_maria.jpg",
    fifa_points: 89,
    biography: "Ailier décisif, vainqueur de la Coupe du Monde 2022.",
    statistics: "700+ matchs",
    trophees_majeurs: "Coupe du Monde, Champions League",
    age: 36,
    club: "Benfica",
    nationalite: "Argentin",
    buts: 130,
    passes: 160,
    cartons_jaunes: 20,
    cartons_rouges: 2,
  },
  {
    id: 80,
    name: "Joaquín",
    posteId: 8,
    country: "Espagne",
    image: "joaquin.jpg",
    fifa_points: 84,
    biography: "Longévité exceptionnelle en Liga.",
    statistics: "800+ matchs",
    trophees_majeurs: "Coupe du Roi",
    age: 43,
    club: "Retraité",
    nationalite: "Espagnol",
    buts: 100,
    passes: 120,
    cartons_jaunes: 25,
    cartons_rouges: 0,
  },
];
