import { Joueur } from '@shared/types/joueurs';

export const attaquantsDeSoutien: Joueur[] = [
  {
    id: 91,
    name: "Diego Maradona",
    posteId: 10,
    country: "Argentine",
    image: "maradona.jpg",
    fifa_points: 98,
    biography: "Légende absolue, auteur de la 'main de Dieu' et du but du siècle.",
    statistics: "490+ matchs",
    trophees_majeurs: "Coupe du Monde 1986",
    age: 60,
    club: "Retraité",
    nationalite: "Argentin",
    buts: 260,
    passes: 160,
    cartons_jaunes: 30,
    cartons_rouges: 5,
  },
  {
    id: 92,
    name: "Pelé",
    posteId: 10,
    country: "Brésil",
    image: "pele.jpg",
    fifa_points: 97,
    biography: "Triple champion du monde, icône planétaire.",
    statistics: "1100+ matchs",
    trophees_majeurs: "Coupes du Monde 1958, 1962, 1970",
    age: 82,
    club: "Retraité",
    nationalite: "Brésilien",
    buts: 767,
    passes: 200,
    cartons_jaunes: 10,
    cartons_rouges: 0,
  },
  {
    id: 93,
    name: "Dennis Bergkamp",
    posteId: 10,
    country: "Pays-Bas",
    image: "bergkamp.jpg",
    fifa_points: 91,
    biography: "Technique et vision hors normes.",
    statistics: "700+ matchs",
    trophees_majeurs: "Premier League, UEFA Cup",
    age: 55,
    club: "Retraité",
    nationalite: "Néerlandais",
    buts: 220,
    passes: 150,
    cartons_jaunes: 20,
    cartons_rouges: 2,
  },
  {
    id: 94,
    name: "Roberto Baggio",
    posteId: 10,
    country: "Italie",
    image: "baggio.jpg",
    fifa_points: 90,
    biography: "Ballon d’Or 1993, grand technicien italien.",
    statistics: "600+ matchs",
    trophees_majeurs: "Ballon d’Or, Serie A",
    age: 57,
    club: "Retraité",
    nationalite: "Italien",
    buts: 240,
    passes: 120,
    cartons_jaunes: 12,
    cartons_rouges: 1,
  },
  {
    id: 95,
    name: "Wayne Rooney",
    posteId: 10,
    country: "Angleterre",
    image: "rooney.jpg",
    fifa_points: 89,
    biography: "Meilleur buteur de l’histoire de Manchester United.",
    statistics: "800+ matchs",
    trophees_majeurs: "Premier League, Champions League",
    age: 39,
    club: "Retraité",
    nationalite: "Anglais",
    buts: 310,
    passes: 190,
    cartons_jaunes: 100,
    cartons_rouges: 6,
  },
  {
    id: 96,
    name: "Carlos Tevez",
    posteId: 10,
    country: "Argentine",
    image: "tevez.jpg",
    fifa_points: 87,
    biography: "Guerrier argentin, décisif en club comme en sélection.",
    statistics: "750+ matchs",
    trophees_majeurs: "Champions League, Copa Libertadores",
    age: 41,
    club: "Retraité",
    nationalite: "Argentin",
    buts: 280,
    passes: 100,
    cartons_jaunes: 80,
    cartons_rouges: 5,
  },
  {
    id: 97,
    name: "Paulo Dybala",
    posteId: 10,
    country: "Argentine",
    image: "dybala.jpg",
    fifa_points: 86,
    biography: "Joueur élégant, champion du monde 2022.",
    statistics: "400+ matchs",
    trophees_majeurs: "Serie A, Coupe du Monde 2022",
    age: 31,
    club: "AS Roma",
    nationalite: "Argentin",
    buts: 140,
    passes: 95,
    cartons_jaunes: 14,
    cartons_rouges: 0,
  },
  {
    id: 98,
    name: "Dries Mertens",
    posteId: 10,
    country: "Belgique",
    image: "mertens.jpg",
    fifa_points: 85,
    biography: "Meilleur buteur de l'histoire de Naples.",
    statistics: "600+ matchs",
    trophees_majeurs: "Coupe d’Italie",
    age: 38,
    club: "Galatasaray",
    nationalite: "Belge",
    buts: 180,
    passes: 130,
    cartons_jaunes: 10,
    cartons_rouges: 0,
  },
  {
    id: 99,
    name: "Alexis Sánchez",
    posteId: 10,
    country: "Chili",
    image: "sanchez.jpg",
    fifa_points: 84,
    biography: "Héros de la Copa América 2015 et 2016.",
    statistics: "600+ matchs",
    trophees_majeurs: "Copa América, FA Cup",
    age: 36,
    club: "Inter Milan",
    nationalite: "Chilien",
    buts: 175,
    passes: 110,
    cartons_jaunes: 20,
    cartons_rouges: 1,
  },
  {
    id: 100,
    name: "João Félix",
    posteId: 10,
    country: "Portugal",
    image: "felix.jpg",
    fifa_points: 83,
    biography: "Talent offensif portugais à fort potentiel.",
    statistics: "250+ matchs",
    trophees_majeurs: "Liga, Nations League",
    age: 26,
    club: "Atlético Madrid",
    nationalite: "Portugais",
    buts: 80,
    passes: 50,
    cartons_jaunes: 10,
    cartons_rouges: 0,
  },
];
