import { Joueur } from '@shared/types/joueurs';

export const buteurs: Joueur[] = [
  {
    id: 101,
    name: "Cristiano Ronaldo",
    posteId: 11,
    country: "Portugal",
    image: "ronaldo.jpg",
    fifa_points: 98,
    biography: "Meilleur buteur de l’histoire du football.",
    statistics: "1200+ matchs",
    trophees_majeurs: "Euro 2016, 5 Ligues des Champions",
    age: 40,
    club: "Al Nassr",
    nationalite: "Portugais",
    buts: 880,
    passes: 250,
    cartons_jaunes: 100,
    cartons_rouges: 11,
  },
  {
    id: 102,
    name: "Lionel Messi",
    posteId: 11,
    country: "Argentine",
    image: "messi.jpg",
    fifa_points: 97,
    biography: "Génie argentin, 8 Ballons d'Or.",
    statistics: "1100+ matchs",
    trophees_majeurs: "Coupe du Monde 2022, 4 Ligues des Champions",
    age: 38,
    club: "Inter Miami",
    nationalite: "Argentin",
    buts: 820,
    passes: 350,
    cartons_jaunes: 85,
    cartons_rouges: 3,
  },
  {
    id: 103,
    name: "Robert Lewandowski",
    posteId: 11,
    country: "Pologne",
    image: "lewandowski.jpg",
    fifa_points: 94,
    biography: "Machine à buts polonaise.",
    statistics: "900+ matchs",
    trophees_majeurs: "Ligue des Champions 2020",
    age: 36,
    club: "FC Barcelone",
    nationalite: "Polonais",
    buts: 650,
    passes: 130,
    cartons_jaunes: 35,
    cartons_rouges: 1,
  },
  {
    id: 104,
    name: "Erling Haaland",
    posteId: 11,
    country: "Norvège",
    image: "haaland.jpg",
    fifa_points: 93,
    biography: "Jeune phénomène du but.",
    statistics: "300+ matchs",
    trophees_majeurs: "Premier League, Ligue des Champions 2023",
    age: 25,
    club: "Manchester City",
    nationalite: "Norvégien",
    buts: 250,
    passes: 60,
    cartons_jaunes: 12,
    cartons_rouges: 0,
  },
  {
    id: 105,
    name: "Karim Benzema",
    posteId: 11,
    country: "France",
    image: "benzema.jpg",
    fifa_points: 92,
    biography: "Ballon d’Or 2022.",
    statistics: "900+ matchs",
    trophees_majeurs: "5 Ligues des Champions",
    age: 37,
    club: "Al-Ittihad",
    nationalite: "Français",
    buts: 430,
    passes: 170,
    cartons_jaunes: 40,
    cartons_rouges: 1,
  },
  {
    id: 106,
    name: "Luis Suárez",
    posteId: 11,
    country: "Uruguay",
    image: "suarez.jpg",
    fifa_points: 91,
    biography: "Redoutable finisseur uruguayen.",
    statistics: "800+ matchs",
    trophees_majeurs: "Copa América 2011, Ligue des Champions 2015",
    age: 38,
    club: "Inter Miami",
    nationalite: "Uruguayen",
    buts: 500,
    passes: 200,
    cartons_jaunes: 90,
    cartons_rouges: 4,
  },
  {
    id: 107,
    name: "Romário",
    posteId: 11,
    country: "Brésil",
    image: "romario.jpg",
    fifa_points: 90,
    biography: "Champion du monde 1994.",
    statistics: "1000+ matchs (selon ses comptes)",
    trophees_majeurs: "Coupe du Monde 1994",
    age: 59,
    club: "Retraité",
    nationalite: "Brésilien",
    buts: 750,
    passes: 120,
    cartons_jaunes: 20,
    cartons_rouges: 1,
  },
  {
    id: 108,
    name: "Marco van Basten",
    posteId: 11,
    country: "Pays-Bas",
    image: "van_basten.jpg",
    fifa_points: 89,
    biography: "Ballon d'Or et star des années 80‑90.",
    statistics: "400+ matchs",
    trophees_majeurs: "Euro 1988, Ligue des Champions",
    age: 60,
    club: "Retraité",
    nationalite: "Néerlandais",
    buts: 300,
    passes: 80,
    cartons_jaunes: 15,
    cartons_rouges: 0,
  },
  {
    id: 109,
    name: "Zlatan Ibrahimović",
    posteId: 11,
    country: "Suède",
    image: "ibrahimovic.jpg",
    fifa_points: 88,
    biography: "Figure charismatique et buteur hors normes.",
    statistics: "900+ matchs",
    trophees_majeurs: "Multiples championnats nationaux",
    age: 43,
    club: "Retraité",
    nationalite: "Suédois",
    buts: 560,
    passes: 140,
    cartons_jaunes: 110,
    cartons_rouges: 10,
  },
  {
    id: 110,
    name: "Gabriel Batistuta",
    posteId: 11,
    country: "Argentine",
    image: "batistuta.jpg",
    fifa_points: 87,
    biography: "Canonnière de la sélection argentine.",
    statistics: "500+ matchs",
    trophees_majeurs: "Copa América",
    age: 56,
    club: "Retraité",
    nationalite: "Argentin",
    buts: 300,
    passes: 50,
    cartons_jaunes: 22,
    cartons_rouges: 1,
  },
];
