import { Joueur } from '@shared/types/joueurs';

export const defenseursDroits: Joueur[] = [
  {
    id: 21,
    name: "Cafu",
    posteId: 3,
    country: "Brésil",
    image: "cafu.jpg",
    fifa_points: 92,
    biography: "Capitaine emblématique du Brésil champion du monde 2002.",
    statistics: "142 sélections",
    trophees_majeurs: "2 Coupes du Monde",
    age: 54,
    club: "Retraité",
    nationalite: "Brésilien",
    buts: 5,
    passes: 25,
    cartons_jaunes: 12,
    cartons_rouges: 1
  },
  {
    id: 22,
    name: "Dani Alves",
    posteId: 3,
    country: "Brésil",
    image: "dani_alves.jpg",
    fifa_points: 90,
    biography: "Joueur le plus titré de l’histoire du football.",
    statistics: "40+ trophées",
    trophees_majeurs: "Ligue des Champions, Copa America",
    age: 41,
    club: "Retraité",
    nationalite: "Brésilien",
    buts: 15,
    passes: 90,
    cartons_jaunes: 30,
    cartons_rouges: 3
  },
  {
    id: 23,
    name: "Philipp Lahm",
    posteId: 3,
    country: "Allemagne",
    image: "lahm.jpg",
    fifa_points: 89,
    biography: "Polyvalent et intelligent, capitaine du Mondial 2014.",
    statistics: "700+ matchs",
    trophees_majeurs: "Coupe du Monde 2014",
    age: 40,
    club: "Retraité",
    nationalite: "Allemand",
    buts: 12,
    passes: 70,
    cartons_jaunes: 10,
    cartons_rouges: 0
  },
  {
    id: 24,
    name: "Carlos Alberto Torres",
    posteId: 3,
    country: "Brésil",
    image: "carlos_alberto.jpg",
    fifa_points: 88,
    biography: "Capitaine de l’équipe brésilienne mythique de 1970.",
    statistics: "500+ matchs",
    trophees_majeurs: "Coupe du Monde 1970",
    age: 72,
    club: "Retraité",
    nationalite: "Brésilien",
    buts: 8,
    passes: 20,
    cartons_jaunes: 4,
    cartons_rouges: 0
  },
  {
    id: 25,
    name: "Lilian Thuram",
    posteId: 3,
    country: "France",
    image: "thuram.jpg",
    fifa_points: 87,
    biography: "Recordman des sélections en équipe de France.",
    statistics: "142 sélections",
    trophees_majeurs: "Coupe du Monde 1998, Euro 2000",
    age: 52,
    club: "Retraité",
    nationalite: "Français",
    buts: 2,
    passes: 15,
    cartons_jaunes: 10,
    cartons_rouges: 1
  },
  {
    id: 26,
    name: "Javier Zanetti",
    posteId: 3,
    country: "Argentine",
    image: "zanetti.jpg",
    fifa_points: 86,
    biography: "Symbole de longévité à l’Inter Milan.",
    statistics: "850+ matchs",
    trophees_majeurs: "Ligue des Champions 2010",
    age: 51,
    club: "Retraité",
    nationalite: "Argentin",
    buts: 12,
    passes: 45,
    cartons_jaunes: 20,
    cartons_rouges: 1
  },
  {
    id: 27,
    name: "Gary Neville",
    posteId: 3,
    country: "Angleterre",
    image: "neville.jpg",
    fifa_points: 85,
    biography: "Fidèle serviteur de Manchester United.",
    statistics: "600+ matchs",
    trophees_majeurs: "Premier League, Ligue des Champions",
    age: 49,
    club: "Retraité",
    nationalite: "Anglais",
    buts: 5,
    passes: 30,
    cartons_jaunes: 35,
    cartons_rouges: 1
  },
  {
    id: 28,
    name: "Bacary Sagna",
    posteId: 3,
    country: "France",
    image: "sagna.jpg",
    fifa_points: 83,
    biography: "Solide défenseur ayant brillé à Arsenal.",
    statistics: "500+ matchs",
    trophees_majeurs: "Finaliste Euro 2016",
    age: 41,
    club: "Retraité",
    nationalite: "Français",
    buts: 2,
    passes: 20,
    cartons_jaunes: 25,
    cartons_rouges: 0
  },
  {
    id: 29,
    name: "Thomas Meunier",
    posteId: 3,
    country: "Belgique",
    image: "meunier.jpg",
    fifa_points: 82,
    biography: "Latéral offensif belge passé par le PSG.",
    statistics: "400+ matchs",
    trophees_majeurs: "3 Championnats de France",
    age: 33,
    club: "Retraité",
    nationalite: "Belge",
    buts: 8,
    passes: 25,
    cartons_jaunes: 10,
    cartons_rouges: 0
  },
  {
    id: 30,
    name: "Héctor Bellerín",
    posteId: 3,
    country: "Espagne",
    image: "bellerin.jpg",
    fifa_points: 81,
    biography: "Latéral rapide d’Arsenal et du Betis.",
    statistics: "300+ matchs",
    trophees_majeurs: "FA Cup",
    age: 30,
    club: "Betis Séville",
    nationalite: "Espagnol",
    buts: 6,
    passes: 20,
    cartons_jaunes: 18,
    cartons_rouges: 0
  }
];
