import { Joueur } from '@shared/types/joueurs';

export const defenseursGauches: Joueur[] = [
  {
    id: 31,
    name: "Paolo Maldini",
    posteId: 4,
    country: "Italie",
    image: "maldini.jpg",
    fifa_points: 92,
    biography: "Légende du Milan AC, défenseur gauche exemplaire.",
    statistics: "900+ matchs",
    trophees_majeurs: "5 Ligues des Champions, 7 Scudetti",
    age: 54,
    club: "Retraité",
    nationalite: "Italien",
    buts: 29,
    passes: 35,
    cartons_jaunes: 45,
    cartons_rouges: 2,
  },
  {
    id: 32,
    name: "Ashley Cole",
    posteId: 4,
    country: "Angleterre",
    image: "cole.jpg",
    fifa_points: 88,
    biography: "Un des meilleurs arrières gauches anglais.",
    statistics: "650+ matchs",
    trophees_majeurs: "Premier League, FA Cup",
    age: 41,
    club: "Retraité",
    nationalite: "Anglais",
    buts: 15,
    passes: 28,
    cartons_jaunes: 30,
    cartons_rouges: 3,
  },
  {
    id: 33,
    name: "Marcelo",
    posteId: 4,
    country: "Brésil",
    image: "marcelo.jpg",
    fifa_points: 89,
    biography: "Arrière gauche brésilien réputé pour son attaque.",
    statistics: "500+ matchs",
    trophees_majeurs: "4 Ligues des Champions, 6 Liga",
    age: 33,
    club: "Real Madrid",
    nationalite: "Brésilien",
    buts: 25,
    passes: 50,
    cartons_jaunes: 40,
    cartons_rouges: 2,
  },
  {
    id: 34,
    name: "Bixente Lizarazu",
    posteId: 4,
    country: "France",
    image: "lizarazu.jpg",
    fifa_points: 86,
    biography: "Champion du Monde 1998, latéral gauche solide.",
    statistics: "450+ matchs",
    trophees_majeurs: "Coupe du Monde, Ligue des Champions",
    age: 48,
    club: "Retraité",
    nationalite: "Français",
    buts: 10,
    passes: 22,
    cartons_jaunes: 25,
    cartons_rouges: 1,
  },
  {
    id: 35,
    name: "Jordi Alba",
    posteId: 4,
    country: "Espagne",
    image: "alba.jpg",
    fifa_points: 87,
    biography: "Latéral gauche rapide et technique.",
    statistics: "400+ matchs",
    trophees_majeurs: "Coupe du Monde, Liga",
    age: 34,
    club: "FC Barcelone",
    nationalite: "Espagnol",
    buts: 18,
    passes: 40,
    cartons_jaunes: 35,
    cartons_rouges: 1,
  },
  {
    id: 36,
    name: "Andrew Robertson",
    posteId: 4,
    country: "Écosse",
    image: "robertson.jpg",
    fifa_points: 85,
    biography: "Défenseur gauche très offensif de Liverpool.",
    statistics: "350+ matchs",
    trophees_majeurs: "Premier League, Ligue des Champions",
    age: 29,
    club: "Liverpool",
    nationalite: "Écossais",
    buts: 7,
    passes: 32,
    cartons_jaunes: 20,
    cartons_rouges: 0,
  },
  {
    id: 37,
    name: "Philipp Lahm",
    posteId: 4,
    country: "Allemagne",
    image: "lahm.jpg",
    fifa_points: 90,
    biography: "Latéral polyvalent et capitaine du Bayern.",
    statistics: "700+ matchs",
    trophees_majeurs: "Coupe du Monde, Bundesliga",
    age: 38,
    club: "Retraité",
    nationalite: "Allemand",
    buts: 20,
    passes: 25,
    cartons_jaunes: 22,
    cartons_rouges: 2,
  },
  {
    id: 38,
    name: "Giuseppe Bergomi",
    posteId: 4,
    country: "Italie",
    image: "bergomi.jpg",
    fifa_points: 85,
    biography: "Défenseur italien très robuste.",
    statistics: "500+ matchs",
    trophees_majeurs: "Coupe du Monde 1982",
    age: 55,
    club: "Retraité",
    nationalite: "Italien",
    buts: 8,
    passes: 12,
    cartons_jaunes: 35,
    cartons_rouges: 3,
  },
  {
    id: 39,
    name: "Nilton Santos",
    posteId: 4,
    country: "Brésil",
    image: "nilton_santos.jpg",
    fifa_points: 87,
    biography: "Pionnier du rôle de latéral offensif.",
    statistics: "700+ matchs",
    trophees_majeurs: "Coupe du Monde",
    age: 87,
    club: "Retraité",
    nationalite: "Brésilien",
    buts: 15,
    passes: 20,
    cartons_jaunes: 30,
    cartons_rouges: 1,
  },
  {
    id: 40,
    name: "Ashley Young",
    posteId: 4,
    country: "Angleterre",
    image: "young.jpg",
    fifa_points: 83,
    biography: "Défenseur polyvalent, ancien ailier.",
    statistics: "600+ matchs",
    trophees_majeurs: "Premier League, FA Cup",
    age: 36,
    club: "Retraité",
    nationalite: "Anglais",
    buts: 12,
    passes: 18,
    cartons_jaunes: 28,
    cartons_rouges: 2,
  },
];
