import { Joueur } from '@shared/types/joueurs';

export const defenseursCentraux: Joueur[] = [
  {
    id: 11,
    name: "Franz Beckenbauer",
    posteId: 2,
    country: "Allemagne",
    image: "beckenbauer.jpg",
    fifa_points: 95,
    biography: "Le Kaiser, icône du football allemand.",
    statistics: "700+ matchs",
    trophees_majeurs: "Coupe du Monde 1974",
    age: 75,
    club: "Retraité",
    nationalite: "Allemand",
    buts: 60,
    passes: 40,
    cartons_jaunes: 12,
    cartons_rouges: 1
  },
  {
    id: 12,
    name: "Paolo Maldini",
    posteId: 2,
    country: "Italie",
    image: "maldini.jpg",
    fifa_points: 93,
    biography: "Légende du Milan AC.",
    statistics: "1000+ matchs",
    trophees_majeurs: "5 Ligues des Champions",
    age: 56,
    club: "Retraité",
    nationalite: "Italien",
    buts: 40,
    passes: 50,
    cartons_jaunes: 30,
    cartons_rouges: 5
  },
  {
    id: 13,
    name: "Sergio Ramos",
    posteId: 2,
    country: "Espagne",
    image: "ramos.jpg",
    fifa_points: 91,
    biography: "Défenseur buteur emblématique du Real Madrid.",
    statistics: "800+ matchs",
    trophees_majeurs: "4 Ligues des Champions",
    age: 38,
    club: "Libre",
    nationalite: "Espagnol",
    buts: 100,
    passes: 25,
    cartons_jaunes: 200,
    cartons_rouges: 26
  },
  {
    id: 14,
    name: "Fabio Cannavaro",
    posteId: 2,
    country: "Italie",
    image: "cannavaro.jpg",
    fifa_points: 89,
    biography: "Ballon d'Or 2006.",
    statistics: "700+ matchs",
    trophees_majeurs: "Coupe du Monde 2006",
    age: 51,
    club: "Retraité",
    nationalite: "Italien",
    buts: 10,
    passes: 20,
    cartons_jaunes: 18,
    cartons_rouges: 2
  },
  {
    id: 15,
    name: "Carles Puyol",
    posteId: 2,
    country: "Espagne",
    image: "puyol.jpg",
    fifa_points: 90,
    biography: "Capitaine emblématique du FC Barcelone.",
    statistics: "600+ matchs",
    trophees_majeurs: "Champions League, Coupe du Monde",
    age: 46,
    club: "Retraité",
    nationalite: "Espagnol",
    buts: 20,
    passes: 18,
    cartons_jaunes: 50,
    cartons_rouges: 3
  },
  {
    id: 16,
    name: "Virgil van Dijk",
    posteId: 2,
    country: "Pays-Bas",
    image: "vandijk.jpg",
    fifa_points: 88,
    biography: "Roi des duels aériens à Liverpool.",
    statistics: "400+ matchs",
    trophees_majeurs: "Ligue des Champions 2019",
    age: 33,
    club: "Liverpool",
    nationalite: "Néerlandais",
    buts: 30,
    passes: 10,
    cartons_jaunes: 15,
    cartons_rouges: 1
  },
  {
    id: 17,
    name: "Thiago Silva",
    posteId: 2,
    country: "Brésil",
    image: "thiagosilva.jpg",
    fifa_points: 87,
    biography: "Longue carrière au plus haut niveau.",
    statistics: "700+ matchs",
    trophees_majeurs: "Copa America",
    age: 39,
    club: "Chelsea",
    nationalite: "Brésilien",
    buts: 20,
    passes: 30,
    cartons_jaunes: 25,
    cartons_rouges: 1
  },
  {
    id: 18,
    name: "Laurent Blanc",
    posteId: 2,
    country: "France",
    image: "blanc.jpg",
    fifa_points: 86,
    biography: "Champion du Monde 1998.",
    statistics: "600+ matchs",
    trophees_majeurs: "Coupe du Monde 1998",
    age: 58,
    club: "Retraité",
    nationalite: "Français",
    buts: 25,
    passes: 22,
    cartons_jaunes: 20,
    cartons_rouges: 2
  },
  {
    id: 19,
    name: "Ronald Koeman",
    posteId: 2,
    country: "Pays-Bas",
    image: "koeman.jpg",
    fifa_points: 88,
    biography: "Un des défenseurs les plus buteurs de l’histoire.",
    statistics: "750+ matchs",
    trophees_majeurs: "EURO 1988",
    age: 61,
    club: "Retraité",
    nationalite: "Néerlandais",
    buts: 200,
    passes: 50,
    cartons_jaunes: 15,
    cartons_rouges: 1
  },
  {
    id: 20,
    name: "Rio Ferdinand",
    posteId: 2,
    country: "Angleterre",
    image: "ferdinand.jpg",
    fifa_points: 85,
    biography: "Pilier de Manchester United pendant une décennie.",
    statistics: "700+ matchs",
    trophees_majeurs: "Champions League 2008",
    age: 46,
    club: "Retraité",
    nationalite: "Anglais",
    buts: 15,
    passes: 18,
    cartons_jaunes: 40,
    cartons_rouges: 3
  }
];
