import { Joueur } from './joueurs';

export const gardiens: Joueur[] = [
 
  {
    posteId: 1,
    id: 1,
    name: 'David De Gea',
    country: 'Espagne',
    image: '/images/degea.jpg',
    fifa_points: 86,
    biography: 'Ancien n°1 de Manchester United, meilleur joueur de MU trois fois d’affilée.',
    statistics: 'Plus de 500 matchs en Premier League',
    trophees_majeurs: 'Premier League 2014, Europa League 2017',
    age: 34,
    club: 'Fiorentina',
    nationalite: 'Espagnol',
    buts: 0,
    passes: 0,
    cartons_jaunes: 25,
    cartons_rouges: 3
  },
  {
    posteId: 1,
    id: 2,
    name: 'Keylor Navas',
    country: 'Costa Rica',
    image: '/images/navas.jpg',
    fifa_points: 87,
    biography: 'Gardien costaricien, plusieurs fois vainqueur de la Ligue des Champions (2016-2018) avec le Real Madrid.',
    statistics: 'Plus de 350 matchs en club',
    trophees_majeurs: 'Champions League 2016, 2017, 2018',
    age: 38,
    club: 'Newell\'s Old Boys',
    nationalite: 'Costaricien',
    buts: 0,
    passes: 0,
    cartons_jaunes: 10,
    cartons_rouges: 1
  },
  {
    posteId: 1,
    id: 3,
    name: 'Raimond Aumann',
    country: 'Allemagne',
    image: '/images/aumann.jpg',
    fifa_points: 83,
    biography: 'Ancien gardien du Bayern Munich, 6 fois champion d’Allemagne dans les années 1980.',
    statistics: '257 matchs en club (216 avec le Bayern)',
    trophees_majeurs: 'Coupe du Monde 1990 (squad)',
    age: 61,
    club: 'Retraité',
    nationalite: 'Allemand',
    buts: 0,
    passes: 0,
    cartons_jaunes: 8,
    cartons_rouges: 0
  },
  {
    posteId: 1,
    id: 4,
    name: 'Oliver Kahn',
    country: 'Allemagne',
    image: '/images/kahn.jpg',
    fifa_points: 90,
    biography: 'Icône allemande, vainqueur de la Ligue des Champions 2001 avec le Bayern et Ballon d’Or 2002 (unique gardien récompensé).',
    statistics: '630 matchs en club',
    trophees_majeurs: 'Champions League 2001',
    age: 56,
    club: 'Retraité',
    nationalite: 'Allemand',
    buts: 0,
    passes: 0,
    cartons_jaunes: 7,
    cartons_rouges: 2
  },
  {
    posteId: 1,
    id: 5,
    name: 'Iker Casillas',
    country: 'Espagne',
    image: '/images/casillas.jpg',
    fifa_points: 88,
    biography: 'Gardien emblématique du Real Madrid et de l’Espagne, champion du Monde 2010 et double champion d’Europe (2008, 2012).',
    statistics: '657 matchs en club',
    trophees_majeurs: 'Coupe du Monde 2010, Euro 2008, 2012',
    age: 44,
    club: 'Retraité',
    nationalite: 'Espagnol',
    buts: 0,
    passes: 0,
    cartons_jaunes: 12,
    cartons_rouges: 1
  },
  {
    posteId: 1,
    id: 6,
    name: 'Peter Schmeichel',
    country: 'Danemark',
    image: '/images/schmeichel.jpg',
    fifa_points: 88,
    biography: 'Héros de Manchester United (triplé 1999) et champion d\'Europe 1992 avec le Danemark.',
    statistics: '648 matchs en club (dont 292 en Premier League)',
    trophees_majeurs: 'Euro 1992, Ligue des Champions 1999',
    age: 61,
    club: 'Retraité',
    nationalite: 'Danois',
    buts: 11,
    passes: 0,
    cartons_jaunes: 15,
    cartons_rouges: 2
  },
  {
    posteId: 1,
    id: 7,
    name: 'Dino Zoff',
    country: 'Italie',
    image: '/images/zoff.jpg',
    fifa_points: 87,
    biography: 'Capitaine de l’Italie, champion du Monde 1982 à 40 ans.',
    statistics: '570 matchs en Serie A (record pendant 20 ans)',
    trophees_majeurs: 'Coupe du Monde 1982',
    age: 81,
    club: 'Retraité',
    nationalite: 'Italien',
    buts: 0,
    passes: 0,
    cartons_jaunes: 10,
    cartons_rouges: 1
  },
  {
    posteId: 1,
    id: 8,
    name: 'Manuel Neuer',
    country: 'Allemagne',
    image: '/images/neuer.jpg',
    fifa_points: 91,
    biography: 'Gardien allemand désormais l’un des meilleurs de sa génération.',
    statistics: 'Plus de 500 matchs en club, record de clean sheets en Bundesliga',
    trophees_majeurs: 'Coupe du Monde 2014, Champions League 2013, 2020',
    age: 39,
    club: 'Bayern Munich',
    nationalite: 'Allemand',
    buts: 0,
    passes: 0,
    cartons_jaunes: 30,
    cartons_rouges: 2
  },
  {
    posteId: 1,
    id: 9,
    name: 'Gianluigi Buffon',
    country: 'Italie',
    image: '/images/buffon.jpg',
    fifa_points: 90,
    biography: 'Légende du football italien, champion du monde 2006.',
    statistics: 'Plus de 1100 matchs professionnels',
    trophees_majeurs: 'Coupe du Monde 2006',
    age: 47,
    club: 'Retraité',
    nationalite: 'Italien',
    buts: 0,
    passes: 10,
    cartons_jaunes: 20,
    cartons_rouges: 1
  },
  {
    posteId: 1,
    id: 10,
    name: 'Lev Yashin',
    country: 'URSS',
    image: '/images/yashin.jpg',
    fifa_points: 91,
    biography: 'Gardien mythique soviétique, seul gardien à avoir remporté le Ballon d\'Or (1963).',
    statistics: '326 matchs avec le Dynamo Moscou',
    trophees_majeurs: 'Médaille d\'or JO 1956, Champion d\'Europe 1960',
    age: 60,
    club: 'Retraité (décédé)',
    nationalite: 'Soviétique',
    buts: 0,
    passes: 0,
    cartons_jaunes: 13,
    cartons_rouges: 0
  }

];
