import { Joueur } from '@shared/types/joueurs';

export const milieuxRelayeurs: Joueur[] = [
  {
    id: 51,
    name: "Luka Modrić",
    posteId: 6,
    country: "Croatie",
    image: "modric.jpg",
    fifa_points: 91,
    biography: "Ballon d’Or 2018, maître du milieu madrilène.",
    statistics: "800+ matchs",
    trophees_majeurs: "Ballon d’Or, Ligue des Champions",
    age: 38,
    club: "Real Madrid",
    nationalite: "Croate",
    buts: 45,
    passes: 100,
    cartons_jaunes: 40,
    cartons_rouges: 2,
  },
  {
    id: 52,
    name: "Xavi Hernández",
    posteId: 6,
    country: "Espagne",
    image: "xavi.jpg",
    fifa_points: 90,
    biography: "Maestro du tiki-taka et du Barça.",
    statistics: "900+ matchs",
    trophees_majeurs: "Coupe du Monde, Champions League",
    age: 45,
    club: "Retraité",
    nationalite: "Espagnol",
    buts: 85,
    passes: 180,
    cartons_jaunes: 35,
    cartons_rouges: 0,
  },
  {
    id: 53,
    name: "Andrés Iniesta",
    posteId: 6,
    country: "Espagne",
    image: "iniesta.jpg",
    fifa_points: 90,
    biography: "Buteur en finale de Coupe du Monde 2010.",
    statistics: "800+ matchs",
    trophees_majeurs: "Coupe du Monde, Champions League",
    age: 40,
    club: "Emirates Club",
    nationalite: "Espagnol",
    buts: 70,
    passes: 160,
    cartons_jaunes: 25,
    cartons_rouges: 0,
  },
  {
    id: 54,
    name: "Steven Gerrard",
    posteId: 6,
    country: "Angleterre",
    image: "gerrard.jpg",
    fifa_points: 89,
    biography: "Légende de Liverpool, leader infatigable.",
    statistics: "700+ matchs",
    trophees_majeurs: "Ligue des Champions 2005",
    age: 44,
    club: "Retraité",
    nationalite: "Anglais",
    buts: 120,
    passes: 90,
    cartons_jaunes: 60,
    cartons_rouges: 8,
  },
  {
    id: 55,
    name: "Frank Lampard",
    posteId: 6,
    country: "Angleterre",
    image: "lampard.jpg",
    fifa_points: 88,
    biography: "Meilleur buteur de l’histoire de Chelsea.",
    statistics: "850+ matchs",
    trophees_majeurs: "Premier League, Champions League",
    age: 46,
    club: "Retraité",
    nationalite: "Anglais",
    buts: 210,
    passes: 100,
    cartons_jaunes: 55,
    cartons_rouges: 3,
  },
  {
    id: 56,
    name: "Paul Pogba",
    posteId: 6,
    country: "France",
    image: "pogba.jpg",
    fifa_points: 86,
    biography: "Talent pur, champion du monde avec la France.",
    statistics: "400+ matchs",
    trophees_majeurs: "Coupe du Monde 2018",
    age: 32,
    club: "Juventus",
    nationalite: "Français",
    buts: 50,
    passes: 55,
    cartons_jaunes: 40,
    cartons_rouges: 3,
  },
  {
    id: 57,
    name: "Toni Kroos",
    posteId: 6,
    country: "Allemagne",
    image: "kroos.jpg",
    fifa_points: 88,
    biography: "Régulateur du Real Madrid et champion du monde 2014.",
    statistics: "750+ matchs",
    trophees_majeurs: "Coupe du Monde, Champions League",
    age: 35,
    club: "Retraité",
    nationalite: "Allemand",
    buts: 80,
    passes: 120,
    cartons_jaunes: 30,
    cartons_rouges: 1,
  },
  {
    id: 58,
    name: "Cesc Fàbregas",
    posteId: 6,
    country: "Espagne",
    image: "fabregas.jpg",
    fifa_points: 86,
    biography: "Milieu créatif formé à Arsenal, passé par le Barça et Chelsea.",
    statistics: "750+ matchs",
    trophees_majeurs: "Euro, Coupe du Monde, Premier League",
    age: 38,
    club: "Retraité",
    nationalite: "Espagnol",
    buts: 70,
    passes: 150,
    cartons_jaunes: 40,
    cartons_rouges: 3,
  },
  {
    id: 59,
    name: "Michael Ballack",
    posteId: 6,
    country: "Allemagne",
    image: "ballack.jpg",
    fifa_points: 87,
    biography: "Milieu complet, leader de la Mannschaft.",
    statistics: "600+ matchs",
    trophees_majeurs: "Bundesliga, Premier League",
    age: 48,
    club: "Retraité",
    nationalite: "Allemand",
    buts: 100,
    passes: 70,
    cartons_jaunes: 65,
    cartons_rouges: 6,
  },
  {
    id: 60,
    name: "Rui Costa",
    posteId: 6,
    country: "Portugal",
    image: "rui_costa.jpg",
    fifa_points: 85,
    biography: "Numéro 10 élégant du Milan AC et de la Seleção.",
    statistics: "550+ matchs",
    trophees_majeurs: "Serie A, Ligue des Champions",
    age: 53,
    club: "Retraité",
    nationalite: "Portugais",
    buts: 65,
    passes: 80,
    cartons_jaunes: 30,
    cartons_rouges: 1,
  },
];
