import { Joueur } from '@shared/types/joueurs';

export const milieuxOffensifs: Joueur[] = [
  {
    id: 61,
    name: "Zinédine Zidane",
    posteId: 7,
    country: "France",
    image: "zidane.jpg",
    fifa_points: 94,
    biography: "Maestro français, champion du monde 1998.",
    statistics: "650+ matchs",
    trophees_majeurs: "Coupe du Monde, Euro, Champions League",
    age: 52,
    club: "Retraité",
    nationalite: "Français",
    buts: 125,
    passes: 100,
    cartons_jaunes: 50,
    cartons_rouges: 10,
  },
  {
    id: 62,
    name: "Ronaldinho",
    posteId: 7,
    country: "Brésil",
    image: "ronaldinho.jpg",
    fifa_points: 93,
    biography: "Magicien brésilien, Ballon d’Or 2005.",
    statistics: "500+ matchs",
    trophees_majeurs: "Coupe du Monde, Champions League",
    age: 45,
    club: "Retraité",
    nationalite: "Brésilien",
    buts: 170,
    passes: 120,
    cartons_jaunes: 30,
    cartons_rouges: 3,
  },
  {
    id: 63,
    name: "Kaká",
    posteId: 7,
    country: "Brésil",
    image: "kaka.jpg",
    fifa_points: 90,
    biography: "Ballon d’Or 2007, star du Milan AC.",
    statistics: "500+ matchs",
    trophees_majeurs: "Coupe du Monde, Champions League",
    age: 42,
    club: "Retraité",
    nationalite: "Brésilien",
    buts: 150,
    passes: 80,
    cartons_jaunes: 20,
    cartons_rouges: 2,
  },
  {
    id: 64,
    name: "Mesut Özil",
    posteId: 7,
    country: "Allemagne",
    image: "ozil.jpg",
    fifa_points: 88,
    biography: "Maître de la passe décisive, champion du monde 2014.",
    statistics: "600+ matchs",
    trophees_majeurs: "Coupe du Monde",
    age: 36,
    club: "Retraité",
    nationalite: "Allemand",
    buts: 90,
    passes: 160,
    cartons_jaunes: 15,
    cartons_rouges: 1,
  },
  {
    id: 65,
    name: "David Silva",
    posteId: 7,
    country: "Espagne",
    image: "david_silva.jpg",
    fifa_points: 87,
    biography: "Petit génie technique, pilier de l’Espagne dorée.",
    statistics: "700+ matchs",
    trophees_majeurs: "Coupe du Monde, Euros, Premier League",
    age: 39,
    club: "Retraité",
    nationalite: "Espagnol",
    buts: 85,
    passes: 140,
    cartons_jaunes: 22,
    cartons_rouges: 0,
  },
  {
    id: 66,
    name: "Hidetoshi Nakata",
    posteId: 7,
    country: "Japon",
    image: "nakata.jpg",
    fifa_points: 85,
    biography: "Légende du football asiatique.",
    statistics: "400+ matchs",
    trophees_majeurs: "Serie A",
    age: 48,
    club: "Retraité",
    nationalite: "Japonais",
    buts: 60,
    passes: 75,
    cartons_jaunes: 18,
    cartons_rouges: 2,
  },
  {
    id: 67,
    name: "James Rodríguez",
    posteId: 7,
    country: "Colombie",
    image: "james.jpg",
    fifa_points: 86,
    biography: "Révélation de la Coupe du Monde 2014.",
    statistics: "450+ matchs",
    trophees_majeurs: "Champions League",
    age: 33,
    club: "São Paulo FC",
    nationalite: "Colombien",
    buts: 95,
    passes: 100,
    cartons_jaunes: 15,
    cartons_rouges: 1,
  },
  {
    id: 68,
    name: "Dejan Savićević",
    posteId: 7,
    country: "Monténégro",
    image: "savicevic.jpg",
    fifa_points: 84,
    biography: "Génie monténégrin du Milan AC des années 90.",
    statistics: "350+ matchs",
    trophees_majeurs: "Ligue des Champions",
    age: 58,
    club: "Retraité",
    nationalite: "Monténégrin",
    buts: 80,
    passes: 60,
    cartons_jaunes: 10,
    cartons_rouges: 1,
  },
  {
    id: 69,
    name: "Valderrama",
    posteId: 7,
    country: "Colombie",
    image: "valderrama.jpg",
    fifa_points: 85,
    biography: "Iconique pour son style et ses passes lumineuses.",
    statistics: "500+ matchs",
    trophees_majeurs: "Championnat Colombien",
    age: 63,
    club: "Retraité",
    nationalite: "Colombien",
    buts: 50,
    passes: 150,
    cartons_jaunes: 5,
    cartons_rouges: 0,
  },
  {
    id: 70,
    name: "Bruno Fernandes",
    posteId: 7,
    country: "Portugal",
    image: "bruno_fernandes.jpg",
    fifa_points: 87,
    biography: "Leader technique de Manchester United.",
    statistics: "400+ matchs",
    trophees_majeurs: "Europa League",
    age: 30,
    club: "Manchester United",
    nationalite: "Portugais",
    buts: 95,
    passes: 110,
    cartons_jaunes: 45,
    cartons_rouges: 1,
  },
];
