import { Joueur } from '@shared/types/joueurs';

export const milieuxDefensifs: Joueur[] = [
  {
    id: 41,
    name: "Claude Makélélé",
    posteId: 5,
    country: "France",
    image: "makelele.jpg",
    fifa_points: 90,
    biography: "Spécialiste du poste de sentinelle, une référence mondiale.",
    statistics: "700+ matchs",
    trophees_majeurs: "Premier League, Liga",
    age: 51,
    club: "Retraité",
    nationalite: "Français",
    buts: 12,
    passes: 25,
    cartons_jaunes: 50,
    cartons_rouges: 4,
  },
  {
    id: 42,
    name: "Sergio Busquets",
    posteId: 5,
    country: "Espagne",
    image: "busquets.jpg",
    fifa_points: 89,
    biography: "Maestro défensif du FC Barcelone.",
    statistics: "700+ matchs",
    trophees_majeurs: "Coupe du Monde, Champions League",
    age: 36,
    club: "Inter Miami",
    nationalite: "Espagnol",
    buts: 15,
    passes: 60,
    cartons_jaunes: 90,
    cartons_rouges: 4,
  },
  {
    id: 43,
    name: "Patrick Vieira",
    posteId: 5,
    country: "France",
    image: "vieira.jpg",
    fifa_points: 88,
    biography: "Puissant et charismatique, pilier d'Arsenal et des Bleus.",
    statistics: "600+ matchs",
    trophees_majeurs: "Coupe du Monde, Premier League",
    age: 48,
    club: "Retraité",
    nationalite: "Français",
    buts: 30,
    passes: 40,
    cartons_jaunes: 70,
    cartons_rouges: 10,
  },
  {
    id: 44,
    name: "Dunga",
    posteId: 5,
    country: "Brésil",
    image: "dunga.jpg",
    fifa_points: 86,
    biography: "Leader du Brésil champion du monde 1994.",
    statistics: "500+ matchs",
    trophees_majeurs: "Coupe du Monde",
    age: 60,
    club: "Retraité",
    nationalite: "Brésilien",
    buts: 20,
    passes: 25,
    cartons_jaunes: 35,
    cartons_rouges: 2,
  },
  {
    id: 45,
    name: "Gennaro Gattuso",
    posteId: 5,
    country: "Italie",
    image: "gattuso.jpg",
    fifa_points: 87,
    biography: "Milieu combatif, moteur du Milan AC.",
    statistics: "600+ matchs",
    trophees_majeurs: "Coupe du Monde, Ligue des Champions",
    age: 47,
    club: "Retraité",
    nationalite: "Italien",
    buts: 10,
    passes: 18,
    cartons_jaunes: 60,
    cartons_rouges: 5,
  },
  {
    id: 46,
    name: "Casemiro",
    posteId: 5,
    country: "Brésil",
    image: "casemiro.jpg",
    fifa_points: 88,
    biography: "Piliers des récents succès du Real Madrid.",
    statistics: "500+ matchs",
    trophees_majeurs: "Ligue des Champions, Copa América",
    age: 32,
    club: "Manchester United",
    nationalite: "Brésilien",
    buts: 25,
    passes: 30,
    cartons_jaunes: 70,
    cartons_rouges: 5,
  },
  {
    id: 47,
    name: "Roy Keane",
    posteId: 5,
    country: "Irlande",
    image: "keane.jpg",
    fifa_points: 87,
    biography: "Capitaine emblématique de Manchester United.",
    statistics: "650+ matchs",
    trophees_majeurs: "Champions League, Premier League",
    age: 53,
    club: "Retraité",
    nationalite: "Irlandais",
    buts: 45,
    passes: 35,
    cartons_jaunes: 80,
    cartons_rouges: 11,
  },
  {
    id: 48,
    name: "Frank Rijkaard",
    posteId: 5,
    country: "Pays-Bas",
    image: "rijkaard.jpg",
    fifa_points: 89,
    biography: "Un des meilleurs milieux défensifs des années 90.",
    statistics: "500+ matchs",
    trophees_majeurs: "Champions League, Euro",
    age: 62,
    club: "Retraité",
    nationalite: "Néerlandais",
    buts: 30,
    passes: 28,
    cartons_jaunes: 22,
    cartons_rouges: 3,
  },
  {
    id: 49,
    name: "Daniele De Rossi",
    posteId: 5,
    country: "Italie",
    image: "derossi.jpg",
    fifa_points: 86,
    biography: "Milieu défensif rugueux de l’AS Roma.",
    statistics: "600+ matchs",
    trophees_majeurs: "Coupe du Monde 2006",
    age: 40,
    club: "Retraité",
    nationalite: "Italien",
    buts: 60,
    passes: 40,
    cartons_jaunes: 85,
    cartons_rouges: 7,
  },
  {
    id: 50,
    name: "N'Golo Kanté",
    posteId: 5,
    country: "France",
    image: "kante.jpg",
    fifa_points: 90,
    biography: "Endurance et humilité au service du collectif.",
    statistics: "500+ matchs",
    trophees_majeurs: "Coupe du Monde, Premier League",
    age: 33,
    club: "Al-Ittihad",
    nationalite: "Français",
    buts: 15,
    passes: 20,
    cartons_jaunes: 40,
    cartons_rouges: 0,
  },
];
